before_all do
  ENV["GITLAB_TOKEN"] = "abcdefg"
end

lane :test do
  create_merge_request(
    api_token: ENV["GITLAB_TOKEN"],
    project_id: "12345",
    title: "WIP: Fastlane Plugin Test",
    body: "It is a test of MR fastlane plugin",
    source: "develop",
    target: "master",
    assignee_id: "0",
    labels: "bot"
  )
end
